# Generated by Django 4.2.16 on 2024-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factureapp', '0002_alter_facture_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='etat',
            field=models.CharField(choices=[('1', 'Payé'), ('0', 'Non payé')], max_length=1),
        ),
    ]
